version: '{build}'

# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2019

#
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
