# Copyright (c) 2010-2024, Lawrence Livermore National Security, LLC. Produced
# at the Lawrence Livermore National Laboratory. All Rights reserved. See files
# LICENSE and NOTICE for details. LLNL-CODE-806117.
#
# This file is part of the MFEM library. For more information and source code
# availability visit https://mfem.org.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.

# GitLab pipeline configuration for the Corona machine at LLNL
variables:
  MACHINE_NAME: corona

.on_corona:
  tags:
    - shell
    - corona
  rules:
    # Don't run corona jobs if...
    # Note: This makes corona an "opt-in" machine. To activate builds on corona
    # for a given GitLab clone of MFEM, go to Setting/CI-CD/variables, and set
    # "ON_CORONA" to "ON". An LC account on for corona is required to trigger a
    # pipeline there.
    - if: '$CI_COMMIT_BRANCH =~ /_cnone/ || $ON_CORONA != "ON"'
      when: never
    # Don't run autotest update if...
    - if: '$CI_JOB_NAME =~ /report/ && $AUTOTEST != "YES"'
      when: never
    # Report success on success status
    - if: '$CI_JOB_NAME =~ /report_job_success/ && $AUTOTEST == "YES"'
      when: on_success
    # Report failure on failure status
    - if: '$CI_JOB_NAME =~ /report_job_failure/ && $AUTOTEST == "YES"'
      when: on_failure
    # Always release resource
    - if: '$CI_JOB_NAME =~ /release_resource/'
      when: always
    # Always cleanup
    - if: '$CI_JOB_NAME =~ /cleanup/'
      when: always
    # Default is to run if previous stage succeeded
    - when: on_success

# Spack helped builds
# Generic corona build job, extending build script
.build_and_test_on_corona:
  extends: [.on_corona]
  stage: build_and_test
  script:
    # THREADS is used by 'tests/gitlab/build_and_test', run below
    - export THREADS=12
    - echo ${ALLOC_NAME}
    - export JOBID=$(squeue -h --name=${ALLOC_NAME} --format=%A)
    - echo ${JOBID}
    - echo ${MFEM_DATA_DIR}
    - echo ${SPEC}
    - srun $( [[ -n "${JOBID}" ]] && echo "--jobid=${JOBID}" ) -t 15 -N 1 tests/gitlab/build_and_test --spec "${SPEC}" --data-dir "${MFEM_DATA_DIR}" --data
