# Copyright (c) 2010-2021, Lawrence Livermore National Security, LLC. Produced
# at the Lawrence Livermore National Laboratory. All Rights reserved. See files
# LICENSE and NOTICE for details. LLNL-CODE-806117.
#
# This file is part of the MFEM library. For more information and source code
# availability visit https://mfem.org.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.

name: build-analysis

permissions:
  actions: write

on:
  push:
    branches:
      - master
      - next
  pull_request:

env:
  HYPRE_ARCHIVE: v2.19.0.tar.gz
  HYPRE_TOP_DIR: hypre-2.19.0
  METIS_ARCHIVE: metis-4.0.3.tar.gz
  METIS_TOP_DIR: metis-4.0.3
  COVERAGE_ENV: mfem-coverage

jobs:
  gitignore:
    # runner.os returns "Linux" instead on the tag used to specify the os
    # (here ubuntu-18.04). We need the tag, so we use a matrix just like
    # in build-and-test workflow.
    strategy:
      matrix:
        os: [ubuntu-18.04]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}

    - name: checkout MFEM
      uses: actions/checkout@v2
      with:
        path: mfem

    - name: Get MPI (Linux)
      run: |
        sudo apt-get install mpich libmpich-dev
        export MAKE_CXX_FLAG="MPICXX=mpic++"

    - name: Cache Hypre Install
      id: hypre-cache
      uses: actions/cache@v2
      with:
        path: ${{ env.HYPRE_TOP_DIR }}
        key: ${{ matrix.os }}-build-${{ env.HYPRE_TOP_DIR }}-87f9e17

    - name: Get Hypre
      if: steps.hypre-cache.outputs.cache-hit != 'true'
      uses: mfem/github-actions/build-hypre@warnings-flags-tweak
      with:
        archive: ${{ env.HYPRE_ARCHIVE }}
        dir: ${{ env.HYPRE_TOP_DIR }}
        target: int32

    - name: Cache Metis Install
      id: metis-cache
      uses: actions/cache@v2
      with:
        path: ${{ env.METIS_TOP_DIR }}
        key: ${{ matrix.os }}-build-${{ env.METIS_TOP_DIR }}-87f9e17

    - name: Install Metis
      if: steps.metis-cache.outputs.cache-hit != 'true'
      uses: mfem/github-actions/build-metis@warnings-flags-tweak
      with:
        archive: ${{ env.METIS_ARCHIVE }}
        dir: ${{ env.METIS_TOP_DIR }}

    # MFEM build and test
    - name: build-mfem
      uses: mfem/github-actions/build-mfem@warnings-flags-tweak
      with:
        os: ${{ matrix.os }}
        target: opt
        codecov: NO
        mpi: par
        build-system: make
        hypre-dir: ${{ env.HYPRE_TOP_DIR }}
        metis-dir: ${{ env.METIS_TOP_DIR }}
        mfem-dir: mfem

    - name: test (no clean)
      run: |
        cd mfem && make test-noclean

    - name: gitignore
      run: |
        cd mfem/tests/scripts
        ./runtest gitignore
